/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hrmanagement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author MY
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtusername1 = new javax.swing.JTextField();
        radioemployee1 = new javax.swing.JRadioButton();
        radiocandidate1 = new javax.swing.JRadioButton();
        buttonlogin1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        buttonregister1 = new javax.swing.JButton();
        pass1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(64, 167, 227));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("LOGIN");
        jLabel4.setToolTipText("");
        jLabel4.setAutoscrolls(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(273, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(270, 270, 270))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("USERNAME");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("PASSWORD");

        txtusername1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusername1ActionPerformed(evt);
            }
        });

        radioemployee1.setText("EMPLOYEE");
        radioemployee1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioemployee1ActionPerformed(evt);
            }
        });

        radiocandidate1.setText("CANDIDATE");
        radiocandidate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiocandidate1ActionPerformed(evt);
            }
        });

        buttonlogin1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonlogin1.setText("LOGIN");
        buttonlogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonlogin1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Not Registered,click here");

        buttonregister1.setText("GO");
        buttonregister1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonregister1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(txtusername1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(pass1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(radioemployee1))
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(radiocandidate1))
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(buttonlogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addGap(5, 5, 5)
                .addComponent(buttonregister1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txtusername1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pass1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(radioemployee1)
                .addGap(0, 0, 0)
                .addComponent(radiocandidate1)
                .addGap(9, 9, 9)
                .addComponent(buttonlogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(buttonregister1))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void radioemployee1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioemployee1ActionPerformed
        if(radioemployee1.isSelected())
        {
            radiocandidate1.setSelected(false);
            
        }
    }//GEN-LAST:event_radioemployee1ActionPerformed

    private void radiocandidate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiocandidate1ActionPerformed
        if(radiocandidate1.isSelected())
        {
            radioemployee1.setSelected(false);
            
        }
    }//GEN-LAST:event_radiocandidate1ActionPerformed
   private Connection con;
  private  PreparedStatement ps;
    private void buttonlogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonlogin1ActionPerformed
        // TODO add your handling code here:
        String username=txtusername1.getText();
        char[] password=pass1.getPassword();
        if(radioemployee1.isSelected())
        {
            
            try {
                con=DriverManager.getConnection("jdbc:mysql://localhost/hrmgtdb", "root", "");
                ps=con.prepareStatement("SELECT 'username','password' FROM `hrlogin` WHERE `username`=? AND `password`=?");
     
                ps.setString(1, username);
                ps.setString(2,String.valueOf(password));
                ResultSet rs=ps.executeQuery();
                if(rs.next())
                {
                    
                    DashboardHR dh=new DashboardHR();
//                    dh.setData(username);
                    dh.setVisible(true);
                    dispose();
                    
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Invalid Username and Password");
                    txtusername1.setText("");
                    pass1.setText("");
                }
            } catch (SQLException ex) {
                Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        else if(radiocandidate1.isSelected())
        {
            try {
                con=DriverManager.getConnection("jdbc:mysql://localhost/hrmgtdb", "root", "");
                ps=con.prepareStatement("SELECT 'username','password' FROM `candrecords` WHERE `username`=? AND `password`=?");
                ps.setString(1, username);
                ps.setString(2,String.valueOf(password));
                ResultSet rs=ps.executeQuery();
                if(rs.next())
                {
                    
                    DashboardCandidate dc=new DashboardCandidate(username);
                    dc.setVisible(true);
                    dispose();
                    
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Invalid Username and Password");
                    txtusername1.setText("");
                    pass1.setText("");
                }
            } catch (SQLException ex) {
                Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            
             
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Select Type of User");
            
        }
    }//GEN-LAST:event_buttonlogin1ActionPerformed

    private void txtusername1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusername1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtusername1ActionPerformed

    private void buttonregister1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonregister1ActionPerformed
        // TODO add your handling code here:
        Registration reg = new Registration();
        reg.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonregister1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonlogin1;
    private javax.swing.JButton buttonregister1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pass1;
    private javax.swing.JRadioButton radiocandidate1;
    private javax.swing.JRadioButton radioemployee1;
    private javax.swing.JTextField txtusername1;
    // End of variables declaration//GEN-END:variables
}
